### ISSUE TITLE
devices = adb.devices() doesnt return

### ISSUE THREAD

**Issue by moyoonthego** [haideralipunjabi/sudoku_automate#1]
Hi Haider,

I'm following your article and trying to replicate a similar process and automation.

However, at the line "devices = adb.devices()" the program freezes and never returns. I've tried different things but I'm not sure what the issue might be. Thought I'd ask. I've attached the code below, if it helps.

def connect_device():
    adb = AdbClient(host='192.168.1.12',port=5555)
    devices = adb.devices()

    if len(devices) == 0:
        print("No Devices Attached")
        quit()
    return devices[0]

**Comment by moyoonthego** [comment]
Looks like an additional block is needed to form connections.

    adb.remote_connect("192.168.1.12", 5555)

THanks anyways haha

**Comment by haideralipunjabi** [comment]
Yeah, I had my device already connected to ADB that's why.
